name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Restore Packages
        run: npm ci
      - name: Check Typescript Types
        run: npm run type-check
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run prettier:check
      - name: Test
        run: npm test
